dist: bionic
before_install:
    - sudo apt-get update
    - sudo apt-get install -y librsvg2-bin optipng

script:
    - bash build.sh

before_deploy:
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"
    - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
    - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
    - git push -q https://$GITHUBTOKEN@github.com/libreofficeid/libreoffice-style-srikandi --tags

deploy:
    provider: releases
    api_key: $GITHUBTOKEN
    file:
        - "README.md"
        - "build/Srikandi-IconSet.oxt"
        - "build/Srikandi-SVG-IconSet.oxt"
        - "build/images_Srikandi.zip"
        - "build/images_Srikandi_svg.zip"
    skip_cleanup: true
    draft: true
    on:
        tags: false
        all_branched: true

branches:
    except:
        - /^*-v[0-9]/
